dist: trusty
language: ruby
rvm:
- 2.3.3
services:
  - postgresql
addons:
  chrome: stable
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- sleep 3
before_install:
- openssl aes-256-cbc -K $encrypted_837fd4b2deec_key -iv $encrypted_837fd4b2deec_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
notifications:
  slack: zakk-ws:lxRYHkgE7M0urCcR1aHPeTvl
