dist: trusty
language: ruby
rvm:
  - 2.4.3
services:
  - postgresql
sudo: required
addons:
  chrome: stable
before_script:
- gem install bundler
- "sudo chown root /opt/google/chrome/chrome-sandbox"
- "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_install:
- openssl aes-256-cbc -K $encrypted_837fd4b2deec_key -iv $encrypted_837fd4b2deec_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
notifications:
  slack: zakk-ws:lxRYHkgE7M0urCcR1aHPeTvl
