language: ruby
rvm:
- 2.3.3
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_install:
- openssl aes-256-cbc -K $encrypted_2f8b813a2d77_key -iv $encrypted_2f8b813a2d77_iv
  -in config/database.yml.enc -out config/database.yml -d
- openssl aes-256-cbc -K $encrypted_2f8b813a2d77_key -iv $encrypted_2f8b813a2d77_iv
  -in config/settings.yml.enc -out config/settings.yml -d
- openssl aes-256-cbc -K $encrypted_2f8b813a2d77_key -iv $encrypted_2f8b813a2d77_iv
  -in config/secrets.yml.enc -out config/secrets.yml -d
- openssl aes-256-cbc -K $encrypted_2f8b813a2d77_key -iv $encrypted_2f8b813a2d77_iv
  -in config/environment.rb.enc -out config/environment.rb -d
- openssl aes-256-cbc -K $encrypted_837fd4b2deec_key -iv $encrypted_837fd4b2deec_iv
  -in config/application.rb.enc -out config/application.rb -d
