dist: xenial
language: ruby
rvm:
  - 2.6.5
services:
  - postgresql
addons:
  chrome: stable
before_script:
- gem install bundler:2.1.4
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- bundle exec rails runner "Webdrivers::Chromedriver.update"
before_install:
- openssl aes-256-cbc -K $encrypted_837fd4b2deec_key -iv $encrypted_837fd4b2deec_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
notifications:
  slack: zakk-ws:lxRYHkgE7M0urCcR1aHPeTvl
cache:
  yarn: true
  bundler: true
