language: ruby
rvm:
 - 2.3
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start